server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8189/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8191/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8193/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter

jwt:
  secret: oifh4309f8h324098fh4398gh8h*&TG*#&Gg97rgff98gf983h4f983h487g*&^F&Fu3r

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
